# sudo: required

group: edge

services:
  - docker

env:
  global:
    - ICINGA2_VERSION=${ICINGA2_VERSION:-2.8.4}
    - BUILD_DATE=$(date +"%Y-%m-%d")

jobs:
  include:
    - stage: build alpine
      script:
        - make alpine
        - make compose-alpine
        - docker-compose --file docker-compose_alpine.yml up --build -d
        - tests/test.sh
        - docker-compose --file docker-compose_alpine.yml kill
        - docker-compose --file docker-compose_alpine.yml down

    - stage: build debian
      script:
        - make debian
        - make compose-debian
        - docker-compose --file docker-compose_debian.yml up --build -d
        - tests/test.sh
        - docker-compose --file docker-compose_debian.yml kill
        - docker-compose --file docker-compose_debian.yml down

    - stage: build alpine and push image
      script:
        - make alpine
        - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
        - docker push ${DOCKER_USERNAME}/docker-icinga2:${ICINGA2_VERSION}-alpine
        - docker push ${DOCKER_USERNAME}/docker-icinga2:${ICINGA2_VERSION}-alpine-master
        - docker push ${DOCKER_USERNAME}/docker-icinga2:${ICINGA2_VERSION}-alpine-satellite
        - docker logout

    - stage: build debian and push image
      script:
        - make debian
        - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
        - docker push ${DOCKER_USERNAME}/docker-icinga2:${ICINGA2_VERSION}-debian
        - docker push ${DOCKER_USERNAME}/docker-icinga2:${ICINGA2_VERSION}-debian-master
        - docker push ${DOCKER_USERNAME}/docker-icinga2:${ICINGA2_VERSION}-debian-satellite
        - docker logout

#    - stage: build, test and push docker image
#      script:
#        - make build
#        - docker-compose --file docker-compose_example.yml up --build -d
#        - tests/test.sh
#        - docker-compose --file docker-compose_example.yml kill
#        - docker-compose --file docker-compose_example.yml down
#        - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
#        - docker push ${DOCKER_USERNAME}/docker-icinga2:${ICINGA2_VERSION}
#        - docker push ${DOCKER_USERNAME}/docker-icinga2:${ICINGA2_VERSION}-master
#        - docker push ${DOCKER_USERNAME}/docker-icinga2:${ICINGA2_VERSION}-satellite
#        - docker tag  ${DOCKER_USERNAME}/docker-icinga2:${ICINGA2_VERSION}           ${DOCKER_USERNAME}/docker-icinga2:latest
#        - docker tag  ${DOCKER_USERNAME}/docker-icinga2:${ICINGA2_VERSION}-master    ${DOCKER_USERNAME}/docker-icinga2:latest-master
#        - docker tag  ${DOCKER_USERNAME}/docker-icinga2:${ICINGA2_VERSION}-satellite ${DOCKER_USERNAME}/docker-icinga2:latest-satellite
#        - docker push ${DOCKER_USERNAME}/docker-icinga2:latest
#        - docker push ${DOCKER_USERNAME}/docker-icinga2:latest-master
#        - docker push ${DOCKER_USERNAME}/docker-icinga2:latest-satellite
