sudo: required

group: edge

services:
  - docker

before_install:
  - docker pull alpine:3.6

install:
  - docker build --tag bodsch/docker-icinga2 .
  - docker run --detach --name icinga2 bodsch/docker-icinga2

script:
  - docker ps | grep -q icinga2

notifications:
  email: false

cache:
  directories:
    - $HOME/docker
