# version: '2.0'


database:
  image: bodsch/docker-mysql:1711.1
  container_name: database
  hostname: database
  ports:
    - 3306:3306
  environment:
    - MYSQL_SYSTEM_USER=root
    - MYSQL_ROOT_PASS=vYUQ14SGVrJRi69PsujC
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /tmp/docker-data/database:/srv

# the Icinga2 Master
# includes a certificate service to create and provide a icinga certificate
icinga2-master:
  build: .
  container_name: icinga2-master
  hostname: icinga2-master.matrix.lan
  privileged: true
  ports:
    - 5665:5665
    - 4567:4567
  environment:
    - ICINGA_API_USERS=root:icinga,dashing:dashing,cert:foo-bar
    - MYSQL_HOST=database
    - MYSQL_ROOT_USER=root
    - MYSQL_ROOT_PASS=vYUQ14SGVrJRi69PsujC
    - IDO_PASSWORD=qUVuLTk9oEDUV0A
    # environment variables for the certificates service
    - ICINGA_MASTER=icinga2-master.matrix.lan
    - BASIC_AUTH_USER=foofoo
    - BASIC_AUTH_PASS=barbar
    #
    - ICINGA_CLUSTER=true
    - ICINGA_CERT_SERVICE=true
    - ICINGA_CERT_SERVICE_BA_USER=admin
    - ICINGA_CERT_SERVICE_BA_PASSWORD=admin
    - ICINGA_CERT_SERVICE_API_USER=root
    - ICINGA_CERT_SERVICE_API_PASSWORD=icinga
    - ICINGA_CERT_SERVICE_SERVER=icinga2-master
    - ICINGA_CERT_SERVICE_PORT=4567
    - ICINGA_CERT_SERVICE_PATH=/
    - CARBON_HOST=
    - CARBON_PORT=2003
    - DEMO_DATA=false
  volumes:
    - /tmp/docker-data/icinga2-master:/srv
  links:
    - database:database

# the first icinga2 satellite
# ask the master above for an certificate
#
# this satellite should work, the BA is correct
icinga2-satellite-1:
  build: .
  container_name: icinga2-satellite-1
  hostname: icinga2-satellite-1.matrix.lan
  privileged: true
  environment:
    - ICINGA_CLUSTER=true
    - ICINGA_MASTER=icinga2-master.matrix.lan
    - ICINGA_CERT_SERVICE=true
    - ICINGA_CERT_SERVICE_BA_USER=foofoo
    - ICINGA_CERT_SERVICE_BA_PASSWORD=barbar
    - ICINGA_CERT_SERVICE_API_USER=root
    - ICINGA_CERT_SERVICE_API_PASSWORD=icinga
    - ICINGA_CERT_SERVICE_SERVER=icinga2-master
    - ICINGA_CERT_SERVICE_PORT=4567
    - ICINGA_CERT_SERVICE_PATH=/
  volumes:
    - /tmp/docker-data/icinga2-satellite-1:/srv
  links:
    - icinga2-master:icinga2-master.matrix.lan

# the second icinga2 satellite
# ask the master above for an certificate
#
# this satellite should fail, because the BA is faulty
icinga2-satellite-2:
  build: .
  container_name: icinga2-satellite-2
  hostname: icinga2-satellite-2.matrix.lan
  privileged: true
  environment:
    - ICINGA_CLUSTER=true
    - ICINGA_MASTER=icinga2-master.matrix.lan
    - ICINGA_CERT_SERVICE=true
    - ICINGA_CERT_SERVICE_BA_USER=admin
    - ICINGA_CERT_SERVICE_BA_PASSWORD=admin
    - ICINGA_CERT_SERVICE_API_USER=root
    - ICINGA_CERT_SERVICE_API_PASSWORD=icinga
    - ICINGA_CERT_SERVICE_SERVER=icinga2-master
    - ICINGA_CERT_SERVICE_PORT=4567
    - ICINGA_CERT_SERVICE_PATH=/
  volumes:
    - /tmp/docker-data/icinga2-satellite-2:/srv
  links:
    - icinga2-master:icinga2-master.matrix.lan

# the second icinga2 satellite
# ask the master above for an certificate
#icinga2-agent-2.1:
#  build: .
#  container_name: icinga2-agent-1
#  hostname: icinga2-agent-1.matrix.lan
#  privileged: true
#  environment:
#    - ICINGA_MASTER=icinga2-master.matrix.lan
#    - ICINGA_CERT_PARENT=icinga2-satellite-2
#    - ICINGA_CERT_SERVICE=true
#    - ICINGA_CERT_SERVICE_BA_USER=admin
#    - ICINGA_CERT_SERVICE_BA_PASSWORD=admin
#    - ICINGA_CERT_SERVICE_API_USER=root
#    - ICINGA_CERT_SERVICE_API_PASSWORD=icinga
#    - ICINGA_CERT_SERVICE_SERVER=icinga2-master
#    - ICINGA_CERT_SERVICE_PORT=4567
#    - ICINGA_CERT_SERVICE_PATH=/
#  volumes:
#    - /tmp/docker-data/icinga2-agent-2.1:/srv
#  links:
#    - icinga2-satellite:icinga2-satellite-2.matrix.lan
